#===================================================
# Description: Build v8 enginer using GitHub Actions
# Author: t1an5t
#===================================================


name: BUILD depot_tools

on:
  push:
    branches: [ master ]
  # watch:
  #   types: started

env:
  PATCH_FLAG: false
  COMMIT: 0
  DEPOT_UPLOAD: true
  SRC_UPLOAD: true
  BINARY_UPLOAD: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id  
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    # init ubuntu1804 environment
    - name: init env
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config git subversion curl wget build-essential python3 xz-utils zip p7zip-full
    
    # get depot_tools
    - name: depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo export PATH=\"\$PATH:`pwd`/depot_tools/\" >> ~/.bash_profile
    
    # compress this file
    - name: zip depot_tools
      if: env.DEPOT_UPLOAD == 'true' && !cancelled()
      run: |
        zip -q -r depot_tools.zip depot_tools
        
    
    # upload depot_tools.zip to release
    - name: upload depot_tools
      if: env.DEPOT_UPLOAD == 'true' && !cancelled()
      uses: JasonEtco/upload-to-release@master
      with:
        args: depot_tools.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
